services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code
    volumes:
      - .:/code
      - ./caja-chica-bot-prod-81dfc4656ec5.json:/code/caja-chica-bot-prod-81dfc4656ec5.json
    depends_on:
      - redis
      - db

  worker:
    build: .
    command: celery -A workers.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code
    volumes:
      - .:/code
      - ./caja-chica-bot-prod-81dfc4656ec5.json:/code/caja-chica-bot-prod-81dfc4656ec5.json
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cajachicadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: